// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CheckoutBranch(arg1:string):Promise<void>;

export function Commit(arg1:string):Promise<void>;

export function CreateBranch(arg1:string,arg2:boolean):Promise<void>;

export function DiscardChanges(arg1:string):Promise<void>;

export function GenerateCommitMessage():Promise<string>;

export function GetAIConfig():Promise<services.AIConfig>;

export function GetBranches():Promise<Array<services.Branch>>;

export function GetCurrentRepository():Promise<string>;

export function GetDiff(arg1:string,arg2:boolean):Promise<string>;

export function GetLog(arg1:number):Promise<Array<services.CommitInfo>>;

export function GetRecentRepositories():Promise<Array<string>>;

export function GetRepositoryInfo():Promise<Record<string, any>>;

export function GetStatus():Promise<services.GitStatus>;

export function IsValidGitRepository(arg1:string):Promise<boolean>;

export function OpenFileInEditor(arg1:string):Promise<void>;

export function OpenRepositoryInTerminal():Promise<void>;

export function RemoveRecentRepository(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectRepository(arg1:string):Promise<void>;

export function SetAIConfig(arg1:services.AIConfig):Promise<void>;

export function StageAll():Promise<void>;

export function StageFiles(arg1:Array<string>):Promise<void>;

export function TestAIConnection():Promise<void>;

export function UnstageAll():Promise<void>;

export function UnstageFiles(arg1:Array<string>):Promise<void>;
