// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {git} from '../models';

export function AddRemote(arg1:string,arg2:string):Promise<void>;

export function AddRepository(arg1:string,arg2:string,arg3:string):Promise<models.Repository>;

export function CheckoutBranch(arg1:string):Promise<void>;

export function CheckoutTag(arg1:string):Promise<void>;

export function CloneRepository(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Commit(arg1:string):Promise<void>;

export function CreateBranch(arg1:string,arg2:boolean):Promise<void>;

export function CreateCommand(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Command>;

export function CreatePrompt(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<models.Prompt>;

export function CreateTag(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteBranch(arg1:string,arg2:boolean):Promise<void>;

export function DeleteCommand(arg1:string):Promise<void>;

export function DeletePrompt(arg1:string):Promise<void>;

export function DeleteRepository(arg1:string):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function DiffBranches(arg1:string,arg2:string):Promise<string>;

export function DiscardChanges(arg1:string):Promise<void>;

export function GenerateCommitMessage():Promise<string>;

export function GetAIConfig():Promise<models.AIConfig>;

export function GetAllRepositories():Promise<Array<models.Repository>>;

export function GetBranches():Promise<Array<models.Branch>>;

export function GetCategories():Promise<Array<string>>;

export function GetCommand(arg1:string):Promise<models.Command>;

export function GetCommands():Promise<Array<models.Command>>;

export function GetCommandsByCategory(arg1:string):Promise<Array<models.Command>>;

export function GetCommitDetail(arg1:string):Promise<Record<string, any>>;

export function GetCurrentRepository():Promise<string>;

export function GetDefaultPrompt():Promise<models.Prompt>;

export function GetDiff(arg1:string,arg2:boolean):Promise<string>;

export function GetLog(arg1:number):Promise<Array<models.CommitInfo>>;

export function GetPrompt(arg1:string):Promise<models.Prompt>;

export function GetPrompts():Promise<Array<models.Prompt>>;

export function GetRecentRepositories():Promise<Array<string>>;

export function GetRemoteNames():Promise<Array<string>>;

export function GetRemotes():Promise<Array<models.Remote>>;

export function GetRepository(arg1:string):Promise<models.Repository>;

export function GetRepositoryInfo():Promise<Record<string, any>>;

export function GetStatus():Promise<models.GitStatus>;

export function GetTags():Promise<Array<git.Tag>>;

export function IsValidGitRepository(arg1:string):Promise<boolean>;

export function MergeBranch(arg1:string,arg2:boolean):Promise<void>;

export function OpenFileInEditor(arg1:string):Promise<void>;

export function OpenRepositoryInTerminal():Promise<void>;

export function Pull(arg1:string,arg2:string):Promise<void>;

export function Push(arg1:string):Promise<void>;

export function RemoveRecentRepository(arg1:string):Promise<void>;

export function RemoveRemote(arg1:string):Promise<void>;

export function Reset(arg1:git.ResetType,arg2:string):Promise<void>;

export function Revert(arg1:string,arg2:boolean):Promise<void>;

export function SearchRepositories(arg1:string):Promise<Array<models.Repository>>;

export function SelectDirectory():Promise<string>;

export function SelectRepository(arg1:string):Promise<void>;

export function SetAIConfig(arg1:models.AIConfig):Promise<void>;

export function SetDefaultPrompt(arg1:string):Promise<void>;

export function StageAll():Promise<void>;

export function StageFiles(arg1:Array<string>):Promise<void>;

export function TestAIConnection(arg1:models.AIConfig):Promise<void>;

export function UnstageAll():Promise<void>;

export function UnstageFiles(arg1:Array<string>):Promise<void>;

export function UpdateCommand(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.Command>;

export function UpdatePrompt(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<models.Prompt>;

export function UpdateRepository(arg1:string,arg2:string,arg3:string):Promise<models.Repository>;

export function UpdateRepositoryAlias(arg1:string,arg2:string):Promise<void>;
