// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {git} from '../models';

export function AddRemote(arg1:string,arg2:string):Promise<void>;

export function CheckoutBranch(arg1:string):Promise<void>;

export function CloneRepository(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Commit(arg1:string):Promise<void>;

export function CreateBranch(arg1:string,arg2:boolean):Promise<void>;

export function DiscardChanges(arg1:string):Promise<void>;

export function GenerateCommitMessage():Promise<string>;

export function GetAIConfig():Promise<models.AIConfig>;

export function GetBranches():Promise<Array<models.Branch>>;

export function GetCurrentRepository():Promise<string>;

export function GetDiff(arg1:string,arg2:boolean):Promise<string>;

export function GetLog(arg1:number):Promise<Array<models.CommitInfo>>;

export function GetRecentRepositories():Promise<Array<string>>;

export function GetRemoteNames():Promise<Array<string>>;

export function GetRemotes():Promise<Array<models.Remote>>;

export function GetRepositoryInfo():Promise<Record<string, any>>;

export function GetStatus():Promise<models.GitStatus>;

export function IsValidGitRepository(arg1:string):Promise<boolean>;

export function OpenFileInEditor(arg1:string):Promise<void>;

export function OpenRepositoryInTerminal():Promise<void>;

export function Pull(arg1:string,arg2:string):Promise<void>;

export function Push(arg1:string):Promise<void>;

export function RemoveRecentRepository(arg1:string):Promise<void>;

export function RemoveRemote(arg1:string):Promise<void>;

export function Reset(arg1:git.ResetType,arg2:string):Promise<void>;

export function Revert(arg1:string,arg2:boolean):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectRepository(arg1:string):Promise<void>;

export function SetAIConfig(arg1:models.AIConfig):Promise<void>;

export function StageAll():Promise<void>;

export function StageFiles(arg1:Array<string>):Promise<void>;

export function TestAIConnection(arg1:models.AIConfig):Promise<void>;

export function UnstageAll():Promise<void>;

export function UnstageFiles(arg1:Array<string>):Promise<void>;
