// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRemote(arg1, arg2) {
  return window['go']['main']['App']['AddRemote'](arg1, arg2);
}

export function AddRepository(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRepository'](arg1, arg2, arg3);
}

export function CheckoutBranch(arg1) {
  return window['go']['main']['App']['CheckoutBranch'](arg1);
}

export function CheckoutTag(arg1) {
  return window['go']['main']['App']['CheckoutTag'](arg1);
}

export function CloneRepository(arg1, arg2, arg3) {
  return window['go']['main']['App']['CloneRepository'](arg1, arg2, arg3);
}

export function Commit(arg1) {
  return window['go']['main']['App']['Commit'](arg1);
}

export function CreateBranch(arg1, arg2) {
  return window['go']['main']['App']['CreateBranch'](arg1, arg2);
}

export function CreateCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateCommand'](arg1, arg2, arg3, arg4);
}

export function CreatePrompt(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2, arg3, arg4);
}

export function CreateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2, arg3);
}

export function DeleteBranch(arg1, arg2) {
  return window['go']['main']['App']['DeleteBranch'](arg1, arg2);
}

export function DeleteCommand(arg1) {
  return window['go']['main']['App']['DeleteCommand'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DeleteRepository(arg1) {
  return window['go']['main']['App']['DeleteRepository'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DiffBranches(arg1, arg2) {
  return window['go']['main']['App']['DiffBranches'](arg1, arg2);
}

export function DiscardChanges(arg1) {
  return window['go']['main']['App']['DiscardChanges'](arg1);
}

export function GenerateCommitMessage() {
  return window['go']['main']['App']['GenerateCommitMessage']();
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetAllRepositories() {
  return window['go']['main']['App']['GetAllRepositories']();
}

export function GetBranches() {
  return window['go']['main']['App']['GetBranches']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCommand(arg1) {
  return window['go']['main']['App']['GetCommand'](arg1);
}

export function GetCommands() {
  return window['go']['main']['App']['GetCommands']();
}

export function GetCommandsByCategory(arg1) {
  return window['go']['main']['App']['GetCommandsByCategory'](arg1);
}

export function GetCommitDetail(arg1) {
  return window['go']['main']['App']['GetCommitDetail'](arg1);
}

export function GetCurrentRepository() {
  return window['go']['main']['App']['GetCurrentRepository']();
}

export function GetDefaultPrompt() {
  return window['go']['main']['App']['GetDefaultPrompt']();
}

export function GetDiff(arg1, arg2) {
  return window['go']['main']['App']['GetDiff'](arg1, arg2);
}

export function GetLog(arg1) {
  return window['go']['main']['App']['GetLog'](arg1);
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}

export function GetPrompts() {
  return window['go']['main']['App']['GetPrompts']();
}

export function GetRecentRepositories() {
  return window['go']['main']['App']['GetRecentRepositories']();
}

export function GetRemoteNames() {
  return window['go']['main']['App']['GetRemoteNames']();
}

export function GetRemotes() {
  return window['go']['main']['App']['GetRemotes']();
}

export function GetRepository(arg1) {
  return window['go']['main']['App']['GetRepository'](arg1);
}

export function GetRepositoryInfo() {
  return window['go']['main']['App']['GetRepositoryInfo']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function IsValidGitRepository(arg1) {
  return window['go']['main']['App']['IsValidGitRepository'](arg1);
}

export function MergeBranch(arg1, arg2) {
  return window['go']['main']['App']['MergeBranch'](arg1, arg2);
}

export function OpenFileInEditor(arg1) {
  return window['go']['main']['App']['OpenFileInEditor'](arg1);
}

export function OpenRepositoryInTerminal() {
  return window['go']['main']['App']['OpenRepositoryInTerminal']();
}

export function Pull(arg1, arg2) {
  return window['go']['main']['App']['Pull'](arg1, arg2);
}

export function Push(arg1) {
  return window['go']['main']['App']['Push'](arg1);
}

export function RemoveRecentRepository(arg1) {
  return window['go']['main']['App']['RemoveRecentRepository'](arg1);
}

export function RemoveRemote(arg1) {
  return window['go']['main']['App']['RemoveRemote'](arg1);
}

export function Reset(arg1, arg2) {
  return window['go']['main']['App']['Reset'](arg1, arg2);
}

export function Revert(arg1, arg2) {
  return window['go']['main']['App']['Revert'](arg1, arg2);
}

export function SearchRepositories(arg1) {
  return window['go']['main']['App']['SearchRepositories'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectRepository(arg1) {
  return window['go']['main']['App']['SelectRepository'](arg1);
}

export function SetAIConfig(arg1) {
  return window['go']['main']['App']['SetAIConfig'](arg1);
}

export function SetDefaultPrompt(arg1) {
  return window['go']['main']['App']['SetDefaultPrompt'](arg1);
}

export function StageAll() {
  return window['go']['main']['App']['StageAll']();
}

export function StageFiles(arg1) {
  return window['go']['main']['App']['StageFiles'](arg1);
}

export function TestAIConnection(arg1) {
  return window['go']['main']['App']['TestAIConnection'](arg1);
}

export function UnstageAll() {
  return window['go']['main']['App']['UnstageAll']();
}

export function UnstageFiles(arg1) {
  return window['go']['main']['App']['UnstageFiles'](arg1);
}

export function UpdateCommand(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateCommand'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdatePrompt(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdatePrompt'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateRepository(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateRepository'](arg1, arg2, arg3);
}

export function UpdateRepositoryAlias(arg1, arg2) {
  return window['go']['main']['App']['UpdateRepositoryAlias'](arg1, arg2);
}
